backend:
  name: github

media_folder: "site/static/img"  
public_folder: "img"

collections:  
  - name: "items"
    label: "Item"
    create: true
    identifier_field: it1
    folder: "site/content/item"
    fields:  
      - {label: "it1", name: "it1", widget: "string"}
      - {label: "it2", name: "it2", widget: "string"}