backend:
  name: github
  repo: j0sephh123/awesome-blackwell-a330e9

media_folder: "site/static/img"  
public_folder: "img"
publish_mode: editorial_workflow

collections:  
  - name: "items"
    label: "Item"
    create: true
    identifier_field: it1
    folder: "site/content/item"
    fields:  
      - {label: "it1", name: "it1", widget: "string"}
      - {label: "it2", name: "it2", widget: "string"}